# Generated by Django 3.1.2 on 2021-12-06 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='registration_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
