# Generated by Django 3.1.2 on 2022-02-14 13:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='receipt_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 14, 13, 13, 37, 293027)),
        ),
    ]
