# Generated by Django 3.1.2 on 2022-02-15 08:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0002_auto_20220214_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='receipt_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 15, 8, 50, 58, 420030)),
        ),
    ]
