# Generated by Django 3.1.2 on 2021-12-05 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mipweb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organisation_name', models.CharField(max_length=64)),
                ('amount_pledged', models.DecimalField(decimal_places=2, max_digits=7)),
                ('contact_person_first_name', models.CharField(max_length=128)),
                ('contact_person_middle_name', models.CharField(max_length=128)),
                ('contact_person_last_name', models.CharField(max_length=128)),
                ('contact_person_email', models.EmailField(max_length=254)),
                ('contact_person_function_role', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Expertise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='PartnershipArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('expertise', models.ManyToManyField(to='mipweb.Expertise')),
            ],
        ),
        migrations.AddField(
            model_name='partnership',
            name='partnership_domain',
            field=models.ManyToManyField(to='mipweb.PartnershipArea'),
        ),
    ]
