# Generated by Django 3.1.2 on 2022-02-08 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64)),
                ('middle_name', models.CharField(blank=True, max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('job_function', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectStage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_name', models.CharField(max_length=64)),
                ('project_status', models.CharField(choices=[('Start', 'start'), ('Starting', 'starting'), ('In Progress', 'in-progress'), ('Finishing', 'finishing'), ('Completed', 'completed'), ('Abandoned', 'abandoned'), ('Halted', 'halted'), ('Frozen', 'frozen')], default='Start', max_length=64)),
                ('start_date', models.DateField()),
                ('end_state', models.DateField()),
                ('comment', models.TextField(max_length=324)),
            ],
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organisation_name', models.CharField(max_length=128)),
                ('partneship_type', models.CharField(choices=[('Collaboration', 'collaboration'), ('Demo Request', 'demo request'), ('Hire Us', 'hire us')], default='Demo Request', max_length=64)),
                ('project_name', models.CharField(max_length=128)),
                ('contact_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partner.contactperson')),
                ('project_stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partner.projectstage')),
            ],
        ),
    ]
